In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from wrangle import *

from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, LassoLars, TweedieRegressor
from sklearn.preprocessing import PolynomialFeatures

In [6]:
df = wrangle_zillow()

Reading CSV

In [4]:
df.head().T

,4,6,7,11,14
bedroomcnt,4.0,3.0,3.0,0.0,0.0
bathroomcnt,2.0,4.0,2.0,0.0,0.0
calculatedfinishedsquarefeet,3633.0,1620.0,2077.0,1200.0,171.0
taxvaluedollarcnt,296425.0,847770.0,646760.0,5328.0,6920.0
yearbuilt,2005,2011,1926,1972,1973
taxamount,6941.39,10244.94,7924.68,91.6,255.17
fips,06037,06037,06037,06037,06037
propertylandusedesc,Single Family Residential,Single Family Residential,Single Family Residential,Single Family Residential,Single Family Residential